### ISSUE TITLE
[Crash]: Server fails to load with Better Tridents installed

### ISSUE THREAD

**Issue by Wash113** [Fuzss/bettertridents#1]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.0

### Notes (Required)

Server is failing at start up with Better Tridents. All of the dependencies are up to date. No crash log is being generated since the server never fully starts up so I have submitted my server log twice. It has a direct reference to Better Tridents on line 171. Server launches fine without the mod. This is on a fresh install of Fabric with latest API

### Crash Report (Required)

https://gist.github.com/Wash113/89af7782e73e78a041339140ad78d887

### latest.log (Optional)

https://gist.github.com/Wash113/89af7782e73e78a041339140ad78d887

**Comment by Fuzss** [comment]
Thanks, fixed in v4.0.1. Should be live in a few minutes.

**Comment by Wash113** [comment]
Awesome. Thanks!!
