### ISSUE TITLE
[All supported version suggestion]: Config value to include extended trident support for other "Tridents"

### ISSUE THREAD

**Issue by Shibva** [Fuzss/bettertridents#10]
### Suggestion (Required)

This is a fabric/quilt user of this mod speaking and may as well be a forge player as well. 

There are a few mods out there that add a "trident" like weapon that the player can enchant with loyalty. The problem is that not all of these things have the "smart-return" feature where the trident returns to the last slot it was thrown in.

It may be a real pain to impliment all of them out of the box so why not instead of doing that add a config in the common config that allows for players/users of the mod to add the trident item to it

Or

you could have it work based on tags to determine what things can be returnable; for example:
if a object that can be thrown has the tag `#c:trident` it will cause any trident or trident-like weapon (thats tossable) to be treated as if it was a normal trident

up to you man; this hopefuly also extends the void protection support to them as well

Thanks for taking your time to read this and have a nice day 😄

**Comment by Shibva** [comment]
[Edit: loyalty appears to implement the void protection already regardless]

**Comment by Fuzss** [comment]
Your suggestion is unfortunately not possible. 

The logic of Better Tridents hooks into the vanilla trident item class and thrown trident entity class. If a modded trident does not use those classes or overrides relevant parts there is nothing I can do about it without adding dedicated support which I don't have the time for.
