### ISSUE TITLE
[Crash]: Incompatibility with Combatify

### ISSUE THREAD

**Issue by cntrik** [Fuzss/bettertridents#14]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.1

### Notes (Required)

Crash on initialization
Incompatibility with [Combatify](https://github.com/Alexandra-Myers/Combatify) more specifically with the Cookey Mod which is a library mod embedded in the .jar of Combatify.

### Crash Report (Required)

https://gist.github.com/Afrocntrik/46970f165394745bd73b80cf9beef16b

**Comment by Fuzss** [comment]
https://github.com/Fuzss/puzzleslib/issues/67
