### ISSUE TITLE
[Suggestion]: repair Tridents with Trident Fragments instead of Prismarine Shards

### ISSUE THREAD

**Issue by peow** [Fuzss/bettertridents#17]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.20.1

### Mod Version(s) (Optional)

v8.0.1

### Suggestion (Required)

since Prismarine Shards drop from killing common guardians, it is unfair to be able to use them to repair the Trident, it would be more interesting if you had to kill Elder Guardians

i imagine it like this: one Trident Fragment repairs **100**% of the trident's durability, so you don't need to spend a lot of time looking for ocean monuments

![image](https://github.com/Fuzss/bettertridents/assets/105888751/d3e56d9f-ac7b-4ec8-b3ae-38eacc17f9e7)

----------

if you think this is good idea, please do a update to **1.20.1**

**Comment by Fuzss** [comment]
Materials always repair 25% durability. Shards are way better suited for that than the very rare fragments.
