### ISSUE TITLE
[Crash]: Crash with latest Puzzles Lib

### ISSUE THREAD

**Issue by pajicadvance** [Fuzss/bettertridents#20]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

v21.0.1

### Other Mods Involved (Required)

Yes

### Notes (Required)

Just install the latest Better Tridents and Puzzles Lib and launch the game.

### Crash Report (Required)

https://mclo.gs/z9HgDLI

### latest.log (Optional)

https://mclo.gs/2pKwkw9

**Comment by Fuzss** [comment]
A version for 1.21.1 is now available.
