### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by 48004800** [Fuzss/bettertridents#4]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.1

### Notes (Required)

https://www.curseforge.com/minecraft/mc-mods/amethyst-tools-mod
Amethyst Trident will only increase melee damage but not throw damage under the influence of Impaling

**Comment by Fuzss** [comment]
See this comment: https://github.com/Fuzss/universalenchants/issues/27#issuecomment-1399528611
