### ISSUE TITLE
[Bug]: Trident fragments don't drop

### ISSUE THREAD

**Issue by AspectTy** [Fuzss/bettertridents#6]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.2

### Notes (Required)

In my survival world when i kill an elder guardian it doesnt drop a fragment, ive also tried placing a spawner (i have a data pack that lets me craft spawners) with an elder guardian egg inside butt even then it doesnt drop a fragment

please help

**Comment by Fuzss** [comment]
The additional drop doesn't apply when the vanilla elder guardian loot table is overridden by a data pack. This is a limitation imposed by Forge. 

In that case simply manually add the drop to the data pack loot table.
